# Generated by Django 5.2.7 on 2025-11-27 16:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='datasets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])])),
                ('n_rows', models.IntegerField(blank=True, null=True)),
                ('n_columns', models.IntegerField(blank=True, null=True)),
                ('columns', models.JSONField(blank=True, null=True)),
                ('date_column', models.CharField(blank=True, max_length=100, null=True)),
                ('target_column', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('linear', 'Linear Regression'), ('ridge', 'Ridge Regression'), ('lasso', 'Lasso Regression'), ('rf', 'Random Forest'), ('dt', 'Decision Tree'), ('gbm', 'Gradient Boosting'), ('xgb', 'XGBoost')], max_length=20)),
                ('model_params', models.JSONField(default=dict)),
                ('use_time_features', models.BooleanField(default=True)),
                ('use_lag_features', models.BooleanField(default=True)),
                ('lag_periods', models.JSONField(default=list)),
                ('use_rolling_features', models.BooleanField(default=True)),
                ('rolling_windows', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('predictions', models.JSONField(blank=True, null=True)),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('model_file', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('training_time', models.FloatField(blank=True, null=True)),
                ('n_train_samples', models.IntegerField(blank=True, null=True)),
                ('n_test_samples', models.IntegerField(blank=True, null=True)),
                ('n_features', models.IntegerField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='forecast.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExplainabilityResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('shap_values', models.JSONField(blank=True, null=True)),
                ('shap_base_value', models.FloatField(blank=True, null=True)),
                ('importance_plot', models.TextField(blank=True, null=True)),
                ('shap_summary_plot', models.TextField(blank=True, null=True)),
                ('shap_waterfall_plot', models.TextField(blank=True, null=True)),
                ('explainer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('n_samples_explained', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explainability', to='forecast.forecastrun')),
            ],
        ),
        migrations.CreateModel(
            name='ModelComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('comparison_data', models.JSONField(blank=True, null=True)),
                ('best_model', models.CharField(blank=True, max_length=100, null=True)),
                ('best_metric_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='forecast.dataset')),
                ('forecast_runs', models.ManyToManyField(related_name='comparisons', to='forecast.forecastrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
